name: Build + Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Build + Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: yarn.lock
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Export
        run: |
          export PATH="$PATH::node_modules/.bin"
          next export
          touch out/.nojekyll
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
